%% Exchange Rates Management System
%% View at https://mermaid.live
flowchart TD
  A[Exchange Rates Management System] --> B{Management Action?}
  B -->|Create Exchange Rate| C[Create Exchange Rate Flow]
  B -->|Update Exchange Rate| D[Update Exchange Rate Flow]
  B -->|Delete Exchange Rate| E[Delete Exchange Rate Flow]
  B -->|View Exchange Rates| F[View Exchange Rates Flow]
  B -->|Manage Exchange Rate Status| G[Manage Exchange Rate Status Flow]
  
  %% Create Exchange Rate Flow
  C --> C1[Validate Exchange Rate Data]
  C1 --> C2[Check for Existing Rate]
  C2 --> C3[Create New Exchange Rate]
  C3 --> C4[Set Exchange Rate Properties]
  C4 --> C5[Save Exchange Rate]
  C5 --> C6[Log Exchange Rate Creation]
  C6 --> C7[Exchange Rate Created]
  
  %% Validate Exchange Rate Data
  C1 --> C1A[Validate from currency]
  C1A --> C1B[Validate to currency]
  C1B --> C1C[Validate rate value]
  C1C --> C1D[Validate base rate]
  C1D --> C1E[Validate effective date]
  C1E --> C1F[Validate expiry date]
  C1F --> C1G[Validate notes]
  C1G --> C1H[Exchange rate data validated]
  
  %% Validate from currency
  C1A --> C1A1[Check currency code format]
  C1A1 --> C1A2[Check currency code validity]
  C1A2 --> C1A3[Check currency support]
  C1A3 --> C1A4[From currency validated]
  
  %% Validate to currency
  C1B --> C1B1[Check currency code format]
  C1B1 --> C1B2[Check currency code validity]
  C1B2 --> C1B3[Check currency support]
  C1B3 --> C1B4[To currency validated]
  
  %% Validate rate value
  C1C --> C1C1[Check rate is positive]
  C1C1 --> C1C2[Check rate is numeric]
  C1C2 --> C1C3[Check rate is reasonable]
  C1C3 --> C1C4[Rate value validated]
  
  %% Validate base rate
  C1D --> C1D1[Check base rate is positive]
  C1D1 --> C1D2[Check base rate is numeric]
  C1D2 --> C1D3[Check base rate is reasonable]
  C1D3 --> C1D4[Base rate validated]
  
  %% Validate effective date
  C1E --> C1E1[Check date format]
  C1E1 --> C1E2[Check date is valid]
  C1E2 --> C1E3[Check date is not in past]
  C1E3 --> C1E4[Effective date validated]
  
  %% Validate expiry date
  C1F --> C1F1[Check date format]
  C1F1 --> C1F2[Check date is valid]
  C1F2 --> C1F3[Check date is after effective date]
  C1F3 --> C1F4[Expiry date validated]
  
  %% Validate notes
  C1G --> C1G1[Check notes length]
  C1G1 --> C1G2[Check notes format]
  C1G2 --> C1G3[Check notes content]
  C1G3 --> C1G4[Notes validated]
  
  %% Check for Existing Rate
  C2 --> C2A[Search for existing rate]
  C2A --> C2B[Check currency pair]
  C2B --> C2C[Check active status]
  C2C --> C2D[Check date overlap]
  C2D --> C2E[Existing rate checked]
  
  %% Search for existing rate
  C2A --> C2A1[Query by from currency]
  C2A1 --> C2A2[Query by to currency]
  C2A2 --> C2A3[Query by active status]
  C2A3 --> C2A4[Existing rate searched]
  
  %% Check currency pair
  C2B --> C2B1[Compare from currency]
  C2B1 --> C2B2[Compare to currency]
  C2B2 --> C2B3[Check pair uniqueness]
  C2B3 --> C2B4[Currency pair checked]
  
  %% Check active status
  C2C --> C2C1[Check isActive flag]
  C2C1 --> C2C2[Check effective date]
  C2C2 --> C2C3[Check expiry date]
  C2C3 --> C2C4[Active status checked]
  
  %% Check date overlap
  C2D --> C2D1[Check effective date overlap]
  C2D1 --> C2D2[Check expiry date overlap]
  C2D2 --> C2D3[Check date range overlap]
  C2D3 --> C2D4[Date overlap checked]
  
  %% Create New Exchange Rate
  C3 --> C3A[Initialize exchange rate object]
  C3A --> C3B[Set basic properties]
  C3B --> C3C[Set rate properties]
  C3C --> C3D[Set metadata]
  C3D --> C3E[Exchange rate object created]
  
  %% Initialize exchange rate object
  C3A --> C3A1[Create new ExchangeRate instance]
  C3A1 --> C3A2[Set default values]
  C3A2 --> C3A3[Set timestamps]
  C3A3 --> C3A4[Exchange rate object initialized]
  
  %% Set basic properties
  C3B --> C3B1[Set fromCurrency]
  C3B1 --> C3B2[Set toCurrency]
  C3B2 --> C3B3[Set isActive to true]
  C3B3 --> C3B4[Set source to manual]
  C3B4 --> C3B5[Basic properties set]
  
  %% Set rate properties
  C3C --> C3C1[Set rate value]
  C3C1 --> C3C2[Set base rate]
  C3C2 --> C3C3[Set buy rate if provided]
  C3C3 --> C3C4[Set sell rate if provided]
  C3C4 --> C3C5[Set spread if provided]
  C3C5 --> C3C6[Rate properties set]
  
  %% Set metadata
  C3D --> C3D1[Set effective date]
  C3D1 --> C3D2[Set expiry date]
  C3D2 --> C3D3[Set notes]
  C3D3 --> C3D4[Set last updated by]
  C3D4 --> C3D5[Set last updated at]
  C3D5 --> C3D6[Metadata set]
  
  %% Set Exchange Rate Properties
  C4 --> C4A[Set from currency]
  C4A --> C4B[Set to currency]
  C4B --> C4C[Set rate value]
  C4C --> C4D[Set base rate]
  C4D --> C4E[Set buy rate]
  C4E --> C4F[Set sell rate]
  C4F --> C4G[Set spread]
  C4G --> C4H[Set source]
  C4H --> C4I[Set effective date]
  C4I --> C4J[Set expiry date]
  C4J --> C4K[Set notes]
  C4K --> C4L[Exchange rate properties set]
  
  %% Set from currency
  C4A --> C4A1[Set fromCurrency field]
  C4A1 --> C4A2[Validate currency code]
  C4A2 --> C4A3[From currency set]
  
  %% Set to currency
  C4B --> C4B1[Set toCurrency field]
  C4B1 --> C4B2[Validate currency code]
  C4B2 --> C4B3[To currency set]
  
  %% Set rate value
  C4C --> C4C1[Set rate field]
  C4C1 --> C4C2[Validate rate value]
  C4C2 --> C4C3[Rate value set]
  
  %% Set base rate
  C4D --> C4D1[Set baseRate field]
  C4D1 --> C4D2[Validate base rate value]
  C4D2 --> C4D3[Base rate set]
  
  %% Set buy rate
  C4E --> C4E1[Set buyRate field if provided]
  C4E1 --> C4E2[Validate buy rate value]
  C4E2 --> C4E3[Buy rate set]
  
  %% Set sell rate
  C4F --> C4F1[Set sellRate field if provided]
  C4F1 --> C4F2[Validate sell rate value]
  C4F2 --> C4F3[Sell rate set]
  
  %% Set spread
  C4G --> C4G1[Set spread field if provided]
  C4G1 --> C4G2[Validate spread value]
  C4G2 --> C4G3[Spread set]
  
  %% Set source
  C4H --> C4H1[Set source field]
  C4H1 --> C4H2[Validate source value]
  C4H2 --> C4H3[Source set]
  
  %% Set effective date
  C4I --> C4I1[Set effectiveDate field]
  C4I1 --> C4I2[Validate effective date]
  C4I2 --> C4I3[Effective date set]
  
  %% Set expiry date
  C4J --> C4J1[Set expiryDate field]
  C4J1 --> C4J2[Validate expiry date]
  C4J2 --> C4J3[Expiry date set]
  
  %% Set notes
  C4K --> C4K1[Set notes field]
  C4K1 --> C4K2[Validate notes content]
  C4K2 --> C4K3[Notes set]
  
  %% Save Exchange Rate
  C5 --> C5A[Save to database]
  C5A --> C5B[Validate save operation]
  C5B --> C5C[Handle save errors]
  C5C --> C5D[Exchange rate saved]
  
  %% Save to database
  C5A --> C5A1[Create database record]
  C5A1 --> C5A2[Set database fields]
  C5A2 --> C5A3[Execute save operation]
  C5A3 --> C5A4[Database record created]
  
  %% Validate save operation
  C5B --> C5B1[Check save success]
  C5B1 --> C5B2[Validate record creation]
  C5B2 --> C5B3[Validate data integrity]
  C5B3 --> C5B4[Save operation validated]
  
  %% Handle save errors
  C5C --> C5C1[Check for save errors]
  C5C1 --> C5C2[Handle validation errors]
  C5C2 --> C5C3[Handle database errors]
  C5C3 --> C5C4[Save errors handled]
  
  %% Log Exchange Rate Creation
  C6 --> C6A[Create log entry]
  C6A --> C6B[Set log details]
  C6B --> C6C[Save log entry]
  C6C --> C6D[Exchange rate creation logged]
  
  %% Create log entry
  C6A --> C6A1[Create log record]
  C6A1 --> C6A2[Set log timestamp]
  C6A2 --> C6A3[Set log action]
  C6A3 --> C6A4[Log entry created]
  
  %% Set log details
  C6B --> C6B1[Set currency pair]
  C6B1 --> C6B2[Set rate value]
  C6B2 --> C6B3[Set created by]
  C6B3 --> C6B4[Set creation timestamp]
  C6B4 --> C6B5[Log details set]
  
  %% Save log entry
  C6C --> C6C1[Save to log database]
  C6C1 --> C6C2[Validate log save]
  C6C2 --> C6C3[Log entry saved]
  
  %% Update Exchange Rate Flow
  D --> D1[Find Exchange Rate]
  D1 --> D2[Validate Update Data]
  D2 --> D3[Update Exchange Rate Properties]
  D3 --> D4[Create History Record]
  D4 --> D5[Save Updated Exchange Rate]
  D5 --> D6[Log Exchange Rate Update]
  D6 --> D7[Exchange Rate Updated]
  
  %% Find Exchange Rate
  D1 --> D1A[Search by currency pair]
  D1A --> D1B[Check active status]
  D1B --> D1C[Validate existence]
  D1C --> D1D[Exchange rate found]
  
  %% Search by currency pair
  D1A --> D1A1[Query by from currency]
  D1A1 --> D1A2[Query by to currency]
  D1A2 --> D1A3[Query by active status]
  D1A3 --> D1A4[Exchange rate searched]
  
  %% Check active status
  D1B --> D1B1[Check isActive flag]
  D1B1 --> D1B2[Check effective date]
  D1B2 --> D1B3[Check expiry date]
  D1B3 --> D1B4[Active status checked]
  
  %% Validate existence
  D1C --> D1C1[Check if rate exists]
  D1C1 --> D1C2[Check if rate is accessible]
  D1C2 --> D1C3[Check if rate can be updated]
  D1C3 --> D1C4[Existence validated]
  
  %% Validate Update Data
  D2 --> D2A[Validate rate value]
  D2A --> D2B[Validate base rate]
  D2B --> D2C[Validate buy rate]
  D2C --> D2D[Validate sell rate]
  D2D --> D2E[Validate effective date]
  D2E --> D2F[Validate expiry date]
  D2F --> D2G[Validate notes]
  D2G --> D2H[Update data validated]
  
  %% Validate rate value
  D2A --> D2A1[Check rate is positive]
  D2A1 --> D2A2[Check rate is numeric]
  D2A2 --> D2A3[Check rate is reasonable]
  D2A3 --> D2A4[Rate value validated]
  
  %% Validate base rate
  D2B --> D2B1[Check base rate is positive]
  D2B1 --> D2B2[Check base rate is numeric]
  D2B2 --> D2B3[Check base rate is reasonable]
  D2B3 --> D2B4[Base rate validated]
  
  %% Validate buy rate
  D2C --> D2C1[Check buy rate is positive]
  D2C1 --> D2C2[Check buy rate is numeric]
  D2C2 --> D2C3[Check buy rate is reasonable]
  D2C3 --> D2C4[Buy rate validated]
  
  %% Validate sell rate
  D2D --> D2D1[Check sell rate is positive]
  D2D1 --> D2D2[Check sell rate is numeric]
  D2D2 --> D2D3[Check sell rate is reasonable]
  D2D3 --> D2D4[Sell rate validated]
  
  %% Validate effective date
  D2E --> D2E1[Check date format]
  D2E1 --> D2E2[Check date is valid]
  D2E2 --> D2E3[Check date is not in past]
  D2E3 --> D2E4[Effective date validated]
  
  %% Validate expiry date
  D2F --> D2F1[Check date format]
  D2F1 --> D2F2[Check date is valid]
  D2F2 --> D2F3[Check date is after effective date]
  D2F3 --> D2F4[Expiry date validated]
  
  %% Validate notes
  D2G --> D2G1[Check notes length]
  D2G1 --> D2G2[Check notes format]
  D2G2 --> D2G3[Check notes content]
  D2G3 --> D2G4[Notes validated]
  
  %% Update Exchange Rate Properties
  D3 --> D3A[Update rate value]
  D3A --> D3B[Update base rate]
  D3B --> D3C[Update buy rate]
  D3C --> D3D[Update sell rate]
  D3D --> D3E[Update spread]
  D3E --> D3F[Update source]
  D3F --> D3G[Update effective date]
  D3G --> D3H[Update expiry date]
  D3H --> D3I[Update notes]
  D3I --> D3J[Update last updated by]
  D3J --> D3K[Update last updated at]
  D3K --> D3L[Exchange rate properties updated]
  
  %% Update rate value
  D3A --> D3A1[Set new rate value]
  D3A1 --> D3A2[Validate rate change]
  D3A2 --> D3A3[Rate value updated]
  
  %% Update base rate
  D3B --> D3B1[Set new base rate]
  D3B1 --> D3B2[Validate base rate change]
  D3B2 --> D3B3[Base rate updated]
  
  %% Update buy rate
  D3C --> D3C1[Set new buy rate]
  D3C1 --> D3C2[Validate buy rate change]
  D3C2 --> D3C3[Buy rate updated]
  
  %% Update sell rate
  D3D --> D3D1[Set new sell rate]
  D3D1 --> D3D2[Validate sell rate change]
  D3D2 --> D3D3[Sell rate updated]
  
  %% Update spread
  D3E --> D3E1[Set new spread]
  D3E1 --> D3E2[Validate spread change]
  D3E2 --> D3E3[Spread updated]
  
  %% Update source
  D3F --> D3F1[Set new source]
  D3F1 --> D3F2[Validate source change]
  D3F2 --> D3F3[Source updated]
  
  %% Update effective date
  D3G --> D3G1[Set new effective date]
  D3G1 --> D3G2[Validate effective date change]
  D3G2 --> D3G3[Effective date updated]
  
  %% Update expiry date
  D3H --> D3H1[Set new expiry date]
  D3H1 --> D3H2[Validate expiry date change]
  D3H2 --> D3H3[Expiry date updated]
  
  %% Update notes
  D3I --> D3I1[Set new notes]
  D3I1 --> D3I2[Validate notes change]
  D3I2 --> D3I3[Notes updated]
  
  %% Update last updated by
  D3J --> D3J1[Set updated by user]
  D3J1 --> D3J2[Validate user access]
  D3J2 --> D3J3[Last updated by updated]
  
  %% Update last updated at
  D3K --> D3K1[Set updated timestamp]
  D3K1 --> D3K2[Validate timestamp]
  D3K2 --> D3K3[Last updated at updated]
  
  %% Create History Record
  D4 --> D4A[Create history entry]
  D4A --> D4B[Set old rate value]
  D4B --> D4C[Set new rate value]
  D4C --> D4D[Set change reason]
  D4D --> D4E[Set change timestamp]
  D4E --> D4F[Save history record]
  D4F --> D4G[History record created]
  
  %% Create history entry
  D4A --> D4A1[Create history record]
  D4A1 --> D4A2[Set currency pair]
  D4A2 --> D4A3[Set change type]
  D4A3 --> D4A4[History entry created]
  
  %% Set old rate value
  D4B --> D4B1[Get current rate value]
  D4B1 --> D4B2[Set old rate in history]
  D4B2 --> D4B3[Old rate value set]
  
  %% Set new rate value
  D4C --> D4C1[Get new rate value]
  D4C1 --> D4C2[Set new rate in history]
  D4C2 --> D4C3[New rate value set]
  
  %% Set change reason
  D4D --> D4D1[Get change reason]
  D4D1 --> D4D2[Set change reason in history]
  D4D2 --> D4D3[Change reason set]
  
  %% Set change timestamp
  D4E --> D4E1[Get current timestamp]
  D4E1 --> D4E2[Set change timestamp in history]
  D4E2 --> D4E3[Change timestamp set]
  
  %% Save history record
  D4F --> D4F1[Save to history database]
  D4F1 --> D4F2[Validate history save]
  D4F2 --> D4F3[History record saved]
  
  %% Save Updated Exchange Rate
  D5 --> D5A[Save to database]
  D5A --> D5B[Validate save operation]
  D5B --> D5C[Handle save errors]
  D5C --> D5D[Updated exchange rate saved]
  
  %% Save to database
  D5A --> D5A1[Update database record]
  D5A1 --> D5A2[Set updated fields]
  D5A2 --> D5A3[Execute save operation]
  D5A3 --> D5A4[Database record updated]
  
  %% Validate save operation
  D5B --> D5B1[Check save success]
  D5B1 --> D5B2[Validate record update]
  D5B2 --> D5B3[Validate data integrity]
  D5B3 --> D5B4[Save operation validated]
  
  %% Handle save errors
  D5C --> D5C1[Check for save errors]
  D5C1 --> D5C2[Handle validation errors]
  D5C2 --> D5C3[Handle database errors]
  D5C3 --> D5C4[Save errors handled]
  
  %% Log Exchange Rate Update
  D6 --> D6A[Create log entry]
  D6A --> D6B[Set log details]
  D6B --> D6C[Save log entry]
  D6C --> D6D[Exchange rate update logged]
  
  %% Create log entry
  D6A --> D6A1[Create log record]
  D6A1 --> D6A2[Set log timestamp]
  D6A2 --> D6A3[Set log action]
  D6A3 --> D6A4[Log entry created]
  
  %% Set log details
  D6B --> D6B1[Set currency pair]
  D6B1 --> D6B2[Set old rate value]
  D6B2 --> D6B3[Set new rate value]
  D6B3 --> D6B4[Set updated by]
  D6B4 --> D6B5[Set update timestamp]
  D6B5 --> D6B6[Log details set]
  
  %% Save log entry
  D6C --> D6C1[Save to log database]
  D6C1 --> D6C2[Validate log save]
  D6C2 --> D6C3[Log entry saved]
  
  %% Delete Exchange Rate Flow
  E --> E1[Find Exchange Rate]
  E1 --> E2[Validate Deletion]
  E2 --> E3[Create History Record]
  E3 --> E4[Deactivate Exchange Rate]
  E4 --> E5[Log Exchange Rate Deletion]
  E5 --> E6[Exchange Rate Deleted]
  
  %% Find Exchange Rate
  E1 --> E1A[Search by currency pair]
  E1A --> E1B[Check active status]
  E1B --> E1C[Validate existence]
  E1C --> E1D[Exchange rate found]
  
  %% Search by currency pair
  E1A --> E1A1[Query by from currency]
  E1A1 --> E1A2[Query by to currency]
  E1A2 --> E1A3[Query by active status]
  E1A3 --> E1A4[Exchange rate searched]
  
  %% Check active status
  E1B --> E1B1[Check isActive flag]
  E1B1 --> E1B2[Check effective date]
  E1B2 --> E1B3[Check expiry date]
  E1B3 --> E1B4[Active status checked]
  
  %% Validate existence
  E1C --> E1C1[Check if rate exists]
  E1C1 --> E1C2[Check if rate is accessible]
  E1C2 --> E1C3[Check if rate can be deleted]
  E1C3 --> E1C4[Existence validated]
  
  %% Validate Deletion
  E2 --> E2A[Check if rate is in use]
  E2A --> E2B[Check for dependencies]
  E2B --> E2C[Validate deletion permissions]
  E2C --> E2D[Deletion validated]
  
  %% Check if rate is in use
  E2A --> E2A1[Check active conversions]
  E2A1 --> E2A2[Check pending transactions]
  E2A2 --> E2A3[Check system dependencies]
  E2A3 --> E2A4[Rate usage checked]
  
  %% Check for dependencies
  E2B --> E2B1[Check conversion dependencies]
  E2B1 --> E2B2[Check transaction dependencies]
  E2B2 --> E2B3[Check system dependencies]
  E2B3 --> E2B4[Dependencies checked]
  
  %% Validate deletion permissions
  E2C --> E2C1[Check user permissions]
  E2C1 --> E2C2[Check admin access]
  E2C2 --> E2C3[Check system permissions]
  E2C3 --> E2C4[Deletion permissions validated]
  
  %% Create History Record
  E3 --> E3A[Create deletion history entry]
  E3A --> E3B[Set deletion reason]
  E3B --> E3C[Set deletion timestamp]
  E3C --> E3D[Save deletion history]
  E3D --> E3E[Deletion history created]
  
  %% Create deletion history entry
  E3A --> E3A1[Create history record]
  E3A1 --> E3A2[Set currency pair]
  E3A2 --> E3A3[Set deletion type]
  E3A3 --> E3A4[Deletion history entry created]
  
  %% Set deletion reason
  E3B --> E3B1[Get deletion reason]
  E3B1 --> E3B2[Set deletion reason in history]
  E3B2 --> E3B3[Deletion reason set]
  
  %% Set deletion timestamp
  E3C --> E3C1[Get current timestamp]
  E3C1 --> E3C2[Set deletion timestamp in history]
  E3C2 --> E3C3[Deletion timestamp set]
  
  %% Save deletion history
  E3D --> E3D1[Save to history database]
  E3D1 --> E3D2[Validate history save]
  E3D2 --> E3D3[Deletion history saved]
  
  %% Deactivate Exchange Rate
  E4 --> E4A[Set isActive to false]
  E4A --> E4B[Set deactivation timestamp]
  E4B --> E4C[Update last updated by]
  E4C --> E4D[Save deactivated rate]
  E4D --> E4E[Exchange rate deactivated]
  
  %% Set isActive to false
  E4A --> E4A1[Update isActive flag]
  E4A1 --> E4A2[Validate deactivation]
  E4A2 --> E4A3[isActive flag updated]
  
  %% Set deactivation timestamp
  E4B --> E4B1[Get current timestamp]
  E4B1 --> E4B2[Set deactivation timestamp]
  E4B2 --> E4B3[Deactivation timestamp set]
  
  %% Update last updated by
  E4C --> E4C1[Set updated by user]
  E4C1 --> E4C2[Validate user access]
  E4C2 --> E4C3[Last updated by updated]
  
  %% Save deactivated rate
  E4D --> E4D1[Save to database]
  E4D1 --> E4D2[Validate save operation]
  E4D2 --> E4D3[Deactivated rate saved]
  
  %% Log Exchange Rate Deletion
  E5 --> E5A[Create log entry]
  E5A --> E5B[Set log details]
  E5B --> E5C[Save log entry]
  E5C --> E5D[Exchange rate deletion logged]
  
  %% Create log entry
  E5A --> E5A1[Create log record]
  E5A1 --> E5A2[Set log timestamp]
  E5A2 --> E5A3[Set log action]
  E5A3 --> E5A4[Log entry created]
  
  %% Set log details
  E5B --> E5B1[Set currency pair]
  E5B1 --> E5B2[Set rate value]
  E5B2 --> E5B3[Set deleted by]
  E5B3 --> E5B4[Set deletion timestamp]
  E5B4 --> E5B5[Log details set]
  
  %% Save log entry
  E5C --> E5C1[Save to log database]
  E5C1 --> E5C2[Validate log save]
  E5C2 --> E5C3[Log entry saved]
  
  %% View Exchange Rates Flow
  F --> F1[Get Exchange Rates List]
  F1 --> F2[Filter Exchange Rates]
  F2 --> F3[Sort Exchange Rates]
  F3 --> F4[Paginate Exchange Rates]
  F4 --> F5[Format Exchange Rates]
  F5 --> F6[Exchange Rates Viewed]
  
  %% Get Exchange Rates List
  F1 --> F1A[Query active exchange rates]
  F1A --> F1B[Include currency pairs]
  F1B --> F1C[Include rate values]
  F1C --> F1D[Include metadata]
  F1D --> F1E[Exchange rates list retrieved]
  
  %% Query active exchange rates
  F1A --> F1A1[Query by isActive flag]
  F1A1 --> F1A2[Query by effective date]
  F1A2 --> F1A3[Query by expiry date]
  F1A3 --> F1A4[Active exchange rates queried]
  
  %% Include currency pairs
  F1B --> F1B1[Include from currency]
  F1B1 --> F1B2[Include to currency]
  F1B2 --> F1B3[Include currency pair info]
  F1B3 --> F1B4[Currency pairs included]
  
  %% Include rate values
  F1C --> F1C1[Include rate value]
  F1C1 --> F1C2[Include base rate]
  F1C2 --> F1C3[Include buy rate]
  F1C3 --> F1C4[Include sell rate]
  F1C4 --> F1C5[Include spread]
  F1C5 --> F1C6[Rate values included]
  
  %% Include metadata
  F1D --> F1D1[Include source]
  F1D1 --> F1D2[Include effective date]
  F1D2 --> F1D3[Include expiry date]
  F1D3 --> F1D4[Include last updated]
  F1D4 --> F1D5[Include notes]
  F1D5 --> F1D6[Metadata included]
  
  %% Filter Exchange Rates
  F2 --> F2A[Filter by from currency]
  F2A --> F2B[Filter by to currency]
  F2B --> F2C[Filter by source]
  F2C --> F2D[Filter by date range]
  F2D --> F2E[Filter by active status]
  F2E --> F2F[Exchange rates filtered]
  
  %% Filter by from currency
  F2A --> F2A1[Apply from currency filter]
  F2A1 --> F2A2[Validate filter value]
  F2A2 --> F2A3[From currency filtered]
  
  %% Filter by to currency
  F2B --> F2B1[Apply to currency filter]
  F2B1 --> F2B2[Validate filter value]
  F2B2 --> F2B3[To currency filtered]
  
  %% Filter by source
  F2C --> F2C1[Apply source filter]
  F2C1 --> F2C2[Validate filter value]
  F2C2 --> F2C3[Source filtered]
  
  %% Filter by date range
  F2D --> F2D1[Apply date range filter]
  F2D1 --> F2D2[Validate date range]
  F2D2 --> F2D3[Date range filtered]
  
  %% Filter by active status
  F2E --> F2E1[Apply active status filter]
  F2E1 --> F2E2[Validate filter value]
  F2E2 --> F2E3[Active status filtered]
  
  %% Sort Exchange Rates
  F3 --> F3A[Sort by currency pair]
  F3A --> F3B[Sort by rate value]
  F3B --> F3C[Sort by effective date]
  F3C --> F3D[Sort by last updated]
  F3D --> F3E[Exchange rates sorted]
  
  %% Sort by currency pair
  F3A --> F3A1[Sort by from currency]
  F3A1 --> F3A2[Sort by to currency]
  F3A2 --> F3A3[Currency pair sorted]
  
  %% Sort by rate value
  F3B --> F3B1[Sort by rate value]
  F3B1 --> F3B2[Sort by base rate]
  F3B2 --> F3B3[Rate value sorted]
  
  %% Sort by effective date
  F3C --> F3C1[Sort by effective date]
  F3C1 --> F3C2[Sort by expiry date]
  F3C2 --> F3C3[Effective date sorted]
  
  %% Sort by last updated
  F3D --> F3D1[Sort by last updated at]
  F3D1 --> F3D2[Sort by last updated by]
  F3D2 --> F3D3[Last updated sorted]
  
  %% Paginate Exchange Rates
  F4 --> F4A[Set page size]
  F4A --> F4B[Set page number]
  F4B --> F4C[Calculate offset]
  F4C --> F4D[Apply pagination]
  F4D --> F4E[Exchange rates paginated]
  
  %% Set page size
  F4A --> F4A1[Get page size parameter]
  F4A1 --> F4A2[Validate page size]
  F4A2 --> F4A3[Set default page size]
  F4A3 --> F4A4[Page size set]
  
  %% Set page number
  F4B --> F4B1[Get page number parameter]
  F4B1 --> F4B2[Validate page number]
  F4B2 --> F4B3[Set default page number]
  F4B3 --> F4B4[Page number set]
  
  %% Calculate offset
  F4C --> F4C1[Calculate offset value]
  F4C1 --> F4C2[Validate offset]
  F4C2 --> F4C3[Offset calculated]
  
  %% Apply pagination
  F4D --> F4D1[Apply limit to query]
  F4D1 --> F4D2[Apply offset to query]
  F4D2 --> F4D3[Execute paginated query]
  F4D3 --> F4D4[Pagination applied]
  
  %% Format Exchange Rates
  F5 --> F5A[Format currency pairs]
  F5A --> F5B[Format rate values]
  F5B --> F5C[Format dates]
  F5C --> F5D[Format metadata]
  F5D --> F5E[Exchange rates formatted]
  
  %% Format currency pairs
  F5A --> F5A1[Format from currency]
  F5A1 --> F5A2[Format to currency]
  F5A2 --> F5A3[Format currency pair display]
  F5A3 --> F5A4[Currency pairs formatted]
  
  %% Format rate values
  F5B --> F5B1[Format rate value]
  F5B1 --> F5B2[Format base rate]
  F5B2 --> F5B3[Format buy rate]
  F5B3 --> F5B4[Format sell rate]
  F5B4 --> F5B5[Format spread]
  F5B5 --> F5B6[Rate values formatted]
  
  %% Format dates
  F5C --> F5C1[Format effective date]
  F5C1 --> F5C2[Format expiry date]
  F5C2 --> F5C3[Format last updated]
  F5C3 --> F5C4[Dates formatted]
  
  %% Format metadata
  F5D --> F5D1[Format source]
  F5D1 --> F5D2[Format notes]
  F5D2 --> F5D3[Format last updated by]
  F5D3 --> F5D4[Metadata formatted]
  
  %% Manage Exchange Rate Status Flow
  G --> G1[Activate Exchange Rate]
  G1 --> G2[Deactivate Exchange Rate]
  G2 --> G3[Set Exchange Rate Priority]
  G3 --> G4[Update Exchange Rate Metadata]
  G4 --> G5[Exchange Rate Status Managed]
  
  %% Activate Exchange Rate
  G1 --> G1A[Set isActive to true]
  G1A --> G1B[Set activation timestamp]
  G1B --> G1C[Update last updated by]
  G1C --> G1D[Save activated rate]
  G1D --> G1E[Exchange rate activated]
  
  %% Set isActive to true
  G1A --> G1A1[Update isActive flag]
  G1A1 --> G1A2[Validate activation]
  G1A2 --> G1A3[isActive flag updated]
  
  %% Set activation timestamp
  G1B --> G1B1[Get current timestamp]
  G1B1 --> G1B2[Set activation timestamp]
  G1B2 --> G1B3[Activation timestamp set]
  
  %% Update last updated by
  G1C --> G1C1[Set updated by user]
  G1C1 --> G1C2[Validate user access]
  G1C2 --> G1C3[Last updated by updated]
  
  %% Save activated rate
  G1D --> G1D1[Save to database]
  G1D1 --> G1D2[Validate save operation]
  G1D2 --> G1D3[Activated rate saved]
  
  %% Deactivate Exchange Rate
  G2 --> G2A[Set isActive to false]
  G2A --> G2B[Set deactivation timestamp]
  G2B --> G2C[Update last updated by]
  G2C --> G2D[Save deactivated rate]
  G2D --> G2E[Exchange rate deactivated]
  
  %% Set isActive to false
  G2A --> G2A1[Update isActive flag]
  G2A1 --> G2A2[Validate deactivation]
  G2A2 --> G2A3[isActive flag updated]
  
  %% Set deactivation timestamp
  G2B --> G2B1[Get current timestamp]
  G2B1 --> G2B2[Set deactivation timestamp]
  G2B2 --> G2B3[Deactivation timestamp set]
  
  %% Update last updated by
  G2C --> G2C1[Set updated by user]
  G2C1 --> G2C2[Validate user access]
  G2C2 --> G2C3[Last updated by updated]
  
  %% Save deactivated rate
  G2D --> G2D1[Save to database]
  G2D1 --> G2D2[Validate save operation]
  G2D2 --> G2D3[Deactivated rate saved]
  
  %% Set Exchange Rate Priority
  G3 --> G3A[Set priority level]
  G3A --> G3B[Update priority timestamp]
  G3B --> G3C[Save priority changes]
  G3C --> G3D[Exchange rate priority set]
  
  %% Set priority level
  G3A --> G3A1[Get priority level]
  G3A1 --> G3A2[Validate priority level]
  G3A2 --> G3A3[Set priority in rate]
  G3A3 --> G3A4[Priority level set]
  
  %% Update priority timestamp
  G3B --> G3B1[Get current timestamp]
  G3B1 --> G3B2[Set priority timestamp]
  G3B2 --> G3B3[Priority timestamp updated]
  
  %% Save priority changes
  G3C --> G3C1[Save to database]
  G3C1 --> G3C2[Validate save operation]
  G3C2 --> G3C3[Priority changes saved]
  
  %% Update Exchange Rate Metadata
  G4 --> G4A[Update source information]
  G4A --> G4B[Update API provider]
  G4B --> G4C[Update notes]
  G4C --> G4D[Update custom metadata]
  G4D --> G4E[Exchange rate metadata updated]
  
  %% Update source information
  G4A --> G4A1[Get source information]
  G4A1 --> G4A2[Validate source information]
  G4A2 --> G4A3[Update source in rate]
  G4A3 --> G4A4[Source information updated]
  
  %% Update API provider
  G4B --> G4B1[Get API provider]
  G4B1 --> G4B2[Validate API provider]
  G4B2 --> G4B3[Update API provider in rate]
  G4B3 --> G4B4[API provider updated]
  
  %% Update notes
  G4C --> G4C1[Get notes]
  G4C1 --> G4C2[Validate notes]
  G4C2 --> G4C3[Update notes in rate]
  G4C3 --> G4C4[Notes updated]
  
  %% Update custom metadata
  G4D --> G4D1[Get custom metadata]
  G4D1 --> G4D2[Validate custom metadata]
  G4D2 --> G4D3[Update custom metadata in rate]
  G4D3 --> G4D4[Custom metadata updated]
  
  %% End points
  C7 --> Z[Exchange Rates Management Complete]
  D7 --> Z
  E6 --> Z
  F6 --> Z
  G5 --> Z
