export const analyticsQueryKeys = {
  dashboard: (params: any = {}) => ['analytics', 'dashboard', params],
  overview: (params: any = {}) => ['analytics', 'overview', params],
  kpis: (params: any = {}) => ['analytics', 'kpis', params],
  revenue: (params: any = {}) => ['analytics', 'revenue', params],
  users: (params: any = {}) => ['analytics', 'users', params],
  products: (params: any = {}) => ['analytics', 'products', params],
  services: (params: any = {}) => ['analytics', 'services', params],
  support: (params: any = {}) => ['analytics', 'support', params],
  performance: () => ['analytics', 'performance'],
  advancedSales: (params: any = {}) => ['analytics', 'advanced', 'sales', params],
  advancedProducts: (params: any = {}) => ['analytics', 'advanced', 'products', params],
  advancedCustomers: (params: any = {}) => ['analytics', 'advanced', 'customers', params],
  advancedInventory: (params: any = {}) => ['analytics', 'advanced', 'inventory', params],
  advancedFinancial: (params: any = {}) => ['analytics', 'advanced', 'financial', params],
  advancedCart: (params: any = {}) => ['analytics', 'advanced', 'cart', params],
  advancedMarketing: (params: any = {}) => ['analytics', 'advanced', 'marketing', params],
  realtime: () => ['analytics', 'advanced', 'realtime'],
  quickStats: () => ['analytics', 'advanced', 'quickStats'],
  reports: (params: any = {}) => ['analytics', 'advanced', 'reports', params],
  report: (id: string) => ['analytics', 'advanced', 'reports', id],
  schedules: (params: any = {}) => ['analytics', 'schedules', params],
  schedule: (id: string) => ['analytics', 'schedules', id],
  scheduleStats: () => ['analytics', 'schedules', 'stats'],
  exports: (params: any = {}) => ['analytics', 'exports', params],
  insights: (days?: number) => ['analytics', 'insights', days],
};
